apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-apache
  namespace: hello-apache
spec:
  replicas: 0
  selector:
    matchLabels:
      app: hello-apache
  template:
    metadata:
      labels:
        app: hello-apache
    spec:
      containers:
      - name: apache
        image: ajajkhan1/nginxapp:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
